"""add_unique_constraint_to_fonts

Revision ID: 4d10356cc6d8
Revises: 91a1b031f026
Create Date: 2016-03-24 15:55:01.210608

"""

# revision identifiers, used by Alembic.
revision = '4d10356cc6d8'
down_revision = '91a1b031f026'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ## I had to  create a copy of the fonts table
    ## add the unique constraint to the copy
    ## copy yhe data with insert ignore select
    ## delete from fonts
    ## rename tables
    pass
    # op.create_unique_constraint(None, 'fonts', ['post_script_name'])
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # I don't have the name of the constraint
    pass
    ### end Alembic commands ###
